disabled_rules:
- notification_center_detachment
- nsobject_prefer_isequal
- trailing_whitespace
- closure_end_indentation
- multiline_arguments_brackets

opt_in_rules:
- closure_spacing
- collection_alignment
- closure_end_indentation
- force_unwrapping
- literal_expression_end_indentation
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- number_separator
- operator_usage_whitespace
- overridden_super_call
- sorted_first_last
- sorted_imports
- toggle_bool
- unused_import
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- yoda_condition

excluded:
- Pods
- SideDish/AppDelegate.swift
- IDIllustTests

identifier_name:
    min_length:
        error: 3
    excluded:
        - id
        - URL
        - URL

line_length: 250
