# Uncomment the next line to define a global platform for your project
platform :ios, '13.7'

target 'IDIllust' do

  use_frameworks! 

  pod 'SwiftLint'
  pod 'Kingfisher'

  post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end

end


